# Generated by Django 3.2.18 on 2023-06-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/blog/default.jpg', upload_to='media/blog/'),
        ),
    ]
